# Asychrous reconfig
# Input params:
# target: Host where it should launched
# Sample of usage:
# ansible-playbook -s  -v --extra-vars="target=192.168.5.119 log_file=/tmp/reconfigure.log only_feed=True" async_reconfig.yml
- hosts: $target
  tasks:

  - name: alienvault update and ciao
    shell: /usr/bin/alienvault-update -c -v -d --feed > $log_file && echo $? > $log_file.rc
    async: 600
    poll: 0
    when: only_feed and update_key==""

  - name: alienvault update feed and ciao
    shell: /usr/bin/alienvault-update -c -v -d > $log_file && echo $? > $log_file.rc
    async: 600
    poll: 0
    when: not only_feed and update_key ==""

  - name: alienvault upgrade and ciao
    shell: /usr/bin/alienvault-update -c -v -d -uc=$update_key > $log_file && echo $? > $log_file.rc
    async: 600
    poll: 0
    when: update_key != ""
